### ISSUE TITLE
Создание заказа

### ISSUE THREAD

**Issue by slapoguzov** [slapoguzov/robbers-exchange-backend#7]
План создается автоматические при создании заказа
0. Со счета заказчика списывается сумма вознаграждения
1. Заказ создается в статусе "без организатора", в этом статусе его могут найти только организаторы
2. Организатор находит заказ и в наглую берет его
3. Организатор создает план, где указывает необходимые скиллы
3. После этого заказ переходит в статус "поиск исполнителей" и становится доступен исполнителям
4. Исполнители ищут заказ, в котором есть план с его скиллом
5. Исполнитель в наглую ассаинится на заказ

**Comment by S55078M** [comment]
Добавлено создание заказов
